# Site settings
title: Amaliyo Trading Pty(Ltd)
email: amaliyo.ko@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Amaliyo Trading (PTY) Ltd is a 100% Black female owned company providing superior customer services and empowering women in underdeveloped sectors of South Africa.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amaliyotrading.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  amaliyotrading # Replace with your GitHub username if you plan to host on GitHub Pages

# Build settings
markdown: kramdown
# theme: minima # You can choose other themes or create your own custom theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Recommended for SEO

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
